"""empty message

Revision ID: 04f4f54abd80
Revises: 134d8f734616
Create Date: 2023-03-14 22:49:17.909839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04f4f54abd80'
down_revision = '134d8f734616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_service',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created')
    op.drop_table('ai_service')
    # ### end Alembic commands ###
