""" added json for service model

Revision ID: 0fc25ff57da1
Revises: e5ed22b60e3a
Create Date: 2023-03-20 22:46:35.219548

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0fc25ff57da1'
down_revision = 'e5ed22b60e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_service', sa.Column('params', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_service', 'params')
    # ### end Alembic commands ###
