"""empty message

Revision ID: 134d8f734616
Revises: 53fbd0cb38a5
Create Date: 2023-03-12 14:56:01.265476

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '134d8f734616'
down_revision = '53fbd0cb38a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f('ix_user_company_id'), 'user', ['company_id'], unique=False)
    op.create_foreign_key(None, 'user', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_company_id'), table_name='user')
    op.drop_column('user', 'company_id')
    # ### end Alembic commands ###
