"""empty message

Revision ID: ab5c6a90adcd
Revises: 0fc25ff57da1
Create Date: 2023-03-22 00:06:00.788205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab5c6a90adcd'
down_revision = '0fc25ff57da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('service_id', sa.String(length=32), nullable=True),
    sa.Column('image_result', sa.LargeBinary(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_service_id'), 'entry', ['service_id'], unique=False)
    op.drop_table('ai_service')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_service',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('counter', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('params', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ai_service_pkey')
    )
    op.drop_index(op.f('ix_entry_service_id'), table_name='entry')
    op.drop_table('entry')
    # ### end Alembic commands ###
