"""editing the models

Revision ID: f250655433bc
Revises: 6905ec9e7f1c
Create Date: 2023-05-14 18:37:25.082283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f250655433bc'
down_revision = '6905ec9e7f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'sign_in_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'sign_in_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
